"""Add joined_date field to user

Revision ID: 1a5330bc1528
Revises: c51985799614
Create Date: 2025-05-11 05:19:45.848665

"""

import sqlalchemy as sa

from alembic import op

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '1a5330bc1528'
down_revision: str | None = 'c51985799614'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'user',
        sa.Column(
            'joined_date',
            sa.TIMESTAMP(),
            server_default=sa.text('NOW()'),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'joined_date')
    # ### end Alembic commands ###
