"""Create music_download_queue table

Revision ID: b3734cd2216e
Revises: 1a5330bc1528
Create Date: 2025-05-11 06:20:24.283025

"""

import sqlalchemy as sa

from alembic import op

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'b3734cd2216e'
down_revision: str | None = '1a5330bc1528'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'music_download_queue',
        sa.Column('id', sa.BIGINT(), nullable=False),
        sa.Column('chat_id', sa.BIGINT(), nullable=False),
        sa.Column('bot_message_id', sa.BIGINT(), nullable=False),
        sa.Column('user_message_id', sa.BIGINT(), nullable=False),
        sa.Column('query', sa.String(), nullable=False),
        sa.Column(
            'queued_date',
            sa.TIMESTAMP(),
            server_default=sa.text('NOW()'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('music_download_queue')
    # ### end Alembic commands ###
