"""Initial

Revision ID: c51985799614
Revises:
Create Date: 2025-05-11 04:19:38.207685

"""

import sqlalchemy as sa

from alembic import op

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'c51985799614'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user',
        sa.Column('id', sa.BIGINT(), nullable=False),
        sa.Column('telegram_id', sa.BIGINT(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_user_telegram_id'), 'user', ['telegram_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_telegram_id'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
